"""
Markdown Reporter
------------------
Generates a clean Markdown report of scan results.
"""

from pathlib import Path
from typing import Any


class MarkdownReporter:
    def __init__(self, output_dir: Path):
        self.output_dir = output_dir

    async def generate(self, metadata: dict, results: dict[str, Any]) -> Path:
        lines = []
        target = metadata.get("target", "unknown")

        lines.append(f"# AetherRecon Report — {target}\n")
        lines.append(f"**Profile:** {metadata.get('profile', 'N/A')}  ")
        lines.append(f"**Scan Start:** {metadata.get('timestamp_start', 'N/A')}  ")
        lines.append(f"**Scan End:** {metadata.get('timestamp_end', 'N/A')}  ")
        lines.append(f"**Modules:** {', '.join(metadata.get('modules', []))}\n")
        lines.append("---\n")

        for module_name, mod_results in results.items():
            if module_name in ("timestamp_start", "errors"):
                continue

            lines.append(f"## {module_name.replace('_', ' ').title()}\n")

            if isinstance(mod_results, dict):
                if "error" in mod_results:
                    lines.append(f"⚠ Error: {mod_results['error']}\n")
                else:
                    for k, v in mod_results.items():
                        if isinstance(v, list) and len(v) > 10:
                            lines.append(f"- **{k}:** {len(v)} items\n")
                        else:
                            lines.append(f"- **{k}:** {v}\n")

            elif isinstance(mod_results, list):
                lines.append(f"Found **{len(mod_results)}** results.\n")
                if mod_results and isinstance(mod_results[0], dict):
                    # Create table for first few entries
                    keys = list(mod_results[0].keys())[:5]
                    lines.append("| " + " | ".join(keys) + " |")
                    lines.append("| " + " | ".join(["---"] * len(keys)) + " |")
                    for entry in mod_results[:20]:
                        vals = [str(entry.get(k, ""))[:50] for k in keys]
                        lines.append("| " + " | ".join(vals) + " |")
                    if len(mod_results) > 20:
                        lines.append(f"\n*...and {len(mod_results) - 20} more*\n")
                lines.append("")

            lines.append("")

        # Errors section
        errors = results.get("errors", [])
        if errors:
            lines.append("## Errors\n")
            for err in errors:
                lines.append(f"- ⚠ {err}")
            lines.append("")

        lines.append("---\n")
        lines.append("*Generated by AetherRecon v1.0 — Authorized scanning only.*\n")

        filename = f"aetherrecon_report_{target}.md"
        filepath = self.output_dir / filename
        with open(filepath, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))

        return filepath
